language: node_js

stages:
  - name: test
    if: tag IS blank
  - name: deploy
    if: branch = master AND type != pull_request

notifications:
  email: false

jobs:
  include:
    - stage: test
      node_js: '12'
      after_success:
        - npm install coveralls@^2.11.9 && cat ./coverage/lcov.info | coveralls
    - stage: deploy
      node_js: '12'
      script: npm run typedoc
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: ./docs
    - stage: deploy
      node_js: '12'
      before_script: npm run build
      script: npm run semantic-release
